add simple run test before pushing image

diff --git a/.github/workflows/docker-image-build-pipeline.yml b/.github/workflows/docker-image-build-pipeline.yml
--- a/.github/workflows/docker-image-build-pipeline.yml
+++ b/.github/workflows/docker-image-build-pipeline.yml
@@ -37,6 +37,14 @@ jobs:
         run: |
           docker build --no-cache -t $IMAGE_NAME:$VERSION_TAG .
 
+      - name: Run basic container tests
+        run: |
+          docker run --rm -d --name test-container -p 8080:80 $IMAGE_NAME:$VERSION_TAG
+          sleep 5
+          curl --fail http://localhost:8080 || (echo "Container failed test!" && docker logs test-container && exit 1)
+          docker stop test-container
+        shell: bash
+
       - name: Push Docker image to GHCR
         run: |
           docker push $IMAGE_NAME:$VERSION_TAG
